general.import = [
"~/.config/alacritty/catppuccin-macchiato.toml"
]

terminal.shell = "/usr/bin/fish"

window.dimensions = { columns = 124, lines = 34 }

font.normal = { family = "Fira Code", style = "Regular" }

font.bold = { family = "Fira Code", style = "Bold" }

font.size = 16
