#!/bin/bash

# TODO
#
# Install
#
# * GIT Flow
# * GIT Flow completion: https://github.com/bobthecow/git-flow-completion
# * VLC 3
# * MongoDB Compass
# * Mysql Workbench
# * Yarn
# * NPM
# * Starship
# * NVM
# * Vue CLI
# * Textpander
# * Chrome
# * Insomnia
# * Atom
# * DBeaver
# * Gnome apps + settings (workspace)
#
# * Ansible
# * Terraform
# * Tmux
# * AWS
# * Calibre
# * Now
# * VSCode
# * Arduino
# * Android studio
# * dconf editor
# * Filezilla
# * Gnome tweaks
# * Kubectl
# * https://github.com/ggreer/the_silver_searcher
#
# Backup
#
# * Insomnia
# * Starship
# * Papier (Chrome)
# * Atom unsaved tab
# * OS shortkey
# * Kubectl
# * Yarn
# * NPM
# * Firefox bookmarks
# * MySQL Workbench connections

# read https://www.ubuntupit.com/best-things-to-do-after-installing-ubuntu/
# read https://sites.google.com/site/easylinuxtipsproject/3

# Install nano syntax highlighting
# https://www.if-not-true-then-false.com/2009/tuning-nano-text-editor-with-nanorc/
# https://github.com/scopatz/nanorc

# Current dir (the script can be run from anywhere)
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Packages
#

# GIT
sudo add-apt-repository -y ppa:git-core/ppa

# Starship
wget -q --show-progress https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
tar xvf starship-x86_64-unknown-linux-gnu.tar.gz
sudo mv starship-x86_64-unknown-linux-gnu/starship /usr/local/bin/

# NVM
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh \
  | bash

# Insomnia
wget --quiet -O - https://insomnia.rest/keys/debian-public.key.asc \
  | sudo apt-key add -
echo "deb https://dl.bintray.com/getinsomnia/Insomnia/" \
  | sudo tee -a /etc/apt/sources.list.d/insomnia.list

# Yarn
# Require Node.js to be installed with NVM
wget --quiet -O - https://dl.yarnpkg.com/debian/pubkey.gpg \
  | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" \
  | sudo tee -a /etc/apt/sources.list.d/yarn.list

# Atom
wget --quiet -O - https://packagecloud.io/AtomEditor/atom/gpgkey \
  | sudo apt-key add -
echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" \
  | sudo tee -a /etc/apt/sources.list.d/atom.list

SYSTEM_PACKAGES=$SYSTEM_PACKAGES'
  atom
  bash-completion
  curl
  git
  git-flow
  tmux
  htop
  fonts-firacode
  powertop
  tlp
  tlp-rdw
  insomnia
  preload'

sudo apt-get -y update \
  && sudo apt-get -y upgrade \
  && sudo apt-get -y install $SYSTEM_PACKAGES

# Install Yarn with NVM
# https://yarnpkg.com/lang/en/docs/install/#debian-stable
sudo apt-get install --no-install-recommends yarn

# TLP
sudo tlp start

# Starship
# TODO append to ~/.bashrc
# eval "$(starship init bash)"

#
# Terminal configuration
#

# TODO

# Append to /etc/hosts
# 127.0.0.1        mysql
# 127.0.0.1        rabbitmq

#
# Atom packages
#

apm install --packages-file ../atom/package-list.txt

#
# Yarn packages
#

yarn global add fast-cli @vue/cli

#
# Symlinks
#

# Bash
ln -sfv "${DOTFILES_DIR}/bash/.bash_aliases" "${HOME}/.bash_aliases"
ln -sfv "${DOTFILES_DIR}/bash/.cubynrc" "${HOME}/.cubynrc"

# GIT
ln -sfv "${DOTFILES_DIR}/git/.gitconfig" "${HOME}/.gitconfig"

# Starship
ln -sfv "${DOTFILES_DIR}/starship/starship.toml" "${HOME}/.config/starship.toml"

# Atom
ln -sfv "${DOTFILES_DIR}/atom/config.cson" "${HOME}/.atom/config.cson"
ln -sfv "${DOTFILES_DIR}/atom/keymap.cson" "${HOME}/.atom/keymap.cson"
ln -sfv "${DOTFILES_DIR}/atom/styles.less" "${HOME}/.atom/styles.less"

source "${HOME}/.bash_prompt"

#
# dconf
#

# Center new windows
# Set to: true
# Path: /org/gnome/mutter/center-new-windows

# Make alt+tab only switch on current workspace apps
# https://superuser.com/questions/394376/how-to-prevent-gnome-shells-alttab-from-grouping-windows-from-similar-apps/860001#860001
