#!/bin/bash

# Root permission test
# Run script with sudo, not sudo su -
if [ $USER != 'root' -o $UID != 0 ]; then
    echo 'This script must be run as root (sudo, not sudo su -).'
    exit 1
fi

# Get current dir (so run this script from anywhere)
DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#
# System packages
#

# PPA
add-apt-repository -y ppa:git-core/ppa
add-apt-repository -y ppa:webupd8team/sublime-text-3
add-apt-repository -y ppa:videolan/stable-daily
add-apt-repository -y ppa:nginx/stable
add-apt-repository -y ppa:wireshark-dev/stable 
add-apt-repository -y ppa:webupd8team/atom
curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -

# Laptop only
if [ -d '/sys/class/power_supply' ]; then
    add-apt-repository -y ppa:linrunner/tlp
fi

# Update package list and upgrade system
apt-get -y update && apt-get -y upgrade

# Development
SYSTEM_PACKAGES=$SYSTEM_PACKAGES' curl emacs24 sublime-text-installer atom git nginx nodejs tmux'
# Utils
SYSTEM_PACKAGES=$SYSTEM_PACKAGES' redshift htop iftop'
# Others
SYSTEM_PACKAGES=$SYSTEM_PACKAGES' skype vlc calibre'

# Laptop only
if [ -d '/sys/class/power_supply' ]; then
    SYSTEM_PACKAGES=$SYSTEM_PACKAGES' powertop tlp'
fi

# Packages installation
apt-get -y install $SYSTEM_PACKAGES

# Remove useless packages
apt-get remove -y --purge growisofs totem totem-common libtotem0 gimp-data mintnanny thunderbird pidgin cowsay mintwelcome hexchat

#
# Atom packages
#

apm install --packages-file ../atom/package-list.txt

#
# Symlinks
#

# Bash
ln -sfv "${DOTFILES_DIR}/bash/.bash_aliases" "${HOME}/.bash_aliases"
ln -sfv "${DOTFILES_DIR}/bash/.bash_prompt" "${HOME}/.bash_prompt"
# Redshift
ln -sfv "${DOTFILES_DIR}/redshift/redshift.conf" "${HOME}/redshift/redshift.conf"
# Sublime Text 3
ln -sfv "${DOTFILES_DIR}/sublime_text/Preferences.sublime-settings" "${HOME}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"
ln -sfv "${DOTFILES_DIR}/sublime_text/Package\ Control.sublime-settings" "${HOME}/.config/sublime-text-3/Packages/User/Package\ Control.sublime-settings"
ln -sfv "${DOTFILES_DIR}/sublime_text/Default\ \(Linux\).sublime-keymap" "${HOME}/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap"
# Tmux
ln -sfv "${DOTFILES_DIR}/tmux/.tmux.conf" "${HOME}/.tmux.conf"
# Ruby
ln -sfv "${DOTFILES_DIR}/gemrc/.gemrc" "${HOME}/.gemrc"
# GIT
ln -sfv "${DOTFILES_DIR}/git/.gitconfig" "${HOME}/.gitconfig"
# Atom
ln -sfv "${DOTFILES_DIR}/atom/config.cson" "${HOME}/.atom/config.cson"
ln -sfv "${DOTFILES_DIR}/atom/styles.less" "${HOME}/.atom/styles.less"
# Hyper.js
ln -sfv "${DOTFILES_DIR}/hyper/.hyper.js" "${HOME}/.hyper.js"

source "${HOME}/.bash_prompt"
