add_newline = false

[line_break]
disabled = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[directory]
truncation_length = 3

[nodejs]
symbol = "⬢ "

[package]
display_private = true

[gcloud]
disabled = true

[battery]
disabled = true

[env_var.PUB_SUB_SCOPED_ENV_KEY]
format = "scoped by key [$env_value](yellow)"
