add_newline = false

[line_break]
disabled = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = false

[nodejs]
symbol = "⬢ "

[package]
display_private = true

[gcloud]
disabled = true

[battery]
disabled = true
