# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  #
  # -- Organization --
  #
  - triggers: [":orgId", ":orgid"]
    replace: "pierreSimpleOrg----"
  # Dev - pierre.flauder@arsen.co
  - triggers: [":devUserId", ":devuserid", ":userDevId", ":userdevid"]
    replace: "Yq9yLMif5zS9at6Zx1ItAqhzy0E2"
  # Prod - pierre.flauder@arsen.co
  - triggers: [":prodUserId", ":userProdId", ":produserid", ":userprodid"]
    replace: "OHx4G8K9XCQ6zexl8o4VUgHawk53"

  #
  # -- Partner --
  #
  - triggers: [":partnerId", ":partnerid"]
    replace: "pierrePartner-------"
  # Dev - pierre.flauder+partner@arsen.co
  - triggers: [":devPartnerUserId", ":devpartneruserid", ":userPartnerDevId", ":userpartnerdevid"]
    replace: "eSJksshWJBe1Zhm1KTqQmc4x9em1"
  # Prod - pierre.flauder+partner@arsen.co
  - triggers: [":prodPartnerUserId", ":prodpartneruserid", ":userPartnerProdId", ":userpartnerprodid"]
    replace: "z1l5OE8YFlVWOLIjxu5HECiGLsi1"

  #
  # -- Partner's Organization --
  #
  - triggers: [":partnerOrgId", ":partnerorgid"]
    replace: "pierrePartnerOrg----"

  - triggers: [":warning", ":danger"]
    replace: "⚠️"
  - trigger: ":check"
    replace: "✅"
  - trigger: ":star"
    replace: "⭐"
  - trigger: ":brain"
    replace: "🧠"
  - triggers: [":death", ":skull"]
    replace: "💀"
  - trigger: ":clock"
    replace: "🕑"
  - trigger: ":hourglass"
    replace: "⏳"
  - trigger: ":fire"
    replace: "🔥"
  - trigger: ":thinking"
    replace: "🤔"
  - trigger: ":rocket"
    replace: "🚀"
  - trigger: ":bug"
    replace: "🐞"
  - trigger: ":mail"
    replace: "✉️"
  - trigger: ":idea"
    replace: "💡"
  - trigger: ":stop"
    replace: "🚫"
  - trigger: ":lock"
    replace: "🔒"
  - trigger: ":sparkles"
    replace: "✨"
  - trigger: ":boom"
    replace: "💥"
  - triggers: [":wip", ":work"]
    replace: "🚧"
  - triggers: [":hammer", ":tool"]
    replace: "⚒️"
  - trigger: ":infinite"
    replace: "∞"
  - triggers: [":light", ":event"]
    replace: "⚡"
  - triggers: [":+1"]
    replace: "👍"
  - triggers: [":-1"]
    replace: "👎"
  - trigger: ":cross"
    replace: "❌"
  - trigger: ":fr"
    replace: "🇫🇷"
  - trigger: ":en"
    replace: "🇬🇧"
  - trigger: ":gh-release"
    replace: "gh release create v2.3.4 --generate-notes"
  - trigger: ":email"
    replace: "pierre.flauder@arsen.co"
  - trigger: ":12ft"
    replace: "https://12ft.io/"
  - triggers: [":changelog", ":release"]
    replace: "https://keepachangelog.com/en/1.0.0/"
  - trigger: ":commit"
    replace: "build:"
  - trigger: ":commit"
    replace: "chore:"
  - trigger: ":commit"
    replace: "ci:"
  - trigger: ":commit"
    replace: "docs:"
  - trigger: ":commit"
    replace: "feat:"
  - trigger: ":commit"
    replace: "fix:"
  - trigger: ":commit"
    replace: "perf:"
  - trigger: ":commit"
    replace: "refactor:"
  - trigger: ":commit"
    replace: "release:"
  - trigger: ":commit"
    replace: "revert:"
  - trigger: ":commit"
    replace: "style:"
  - trigger: ":commit"
    replace: "test:"
  - regex: ":refusal(?P<name>[a-zA-Z]+);"
    replace: "Hello {{name}},\n\nLe CTO et moi avons discuté de ta candidature suite à notre entretien. Nous n'allons pas continuer avec ta candidature : nous cherchons un profil avec plus d'expérience en DDD et architecture cloud.\n\nMerci pour ton intérêt pour Arsen et bonne chance dans ta recherche !"
  - trigger: ":refusal"
    replace: "Hello <<NAME>>,\n\nLe CTO et moi avons discuté de ta candidature suite à notre entretien. Nous n'allons pas continuer avec ta candidature : nous cherchons un profil avec plus d'expérience en DDD et architecture cloud.\n\nMerci pour ton intérêt pour Arsen et bonne chance dans ta recherche !"
  - trigger: ":screen"
    replace: |
             Screen call {{now}}

             - Qu'est ce que tu as retenu d'Arsen ?
             - Pourquoi tu pars ?
             - Tu cherches quoi ?
             - Prétentions salariales ?
             - Early ?
             - Remote ?
             - Disponibilité ?

             PRO

             CON
    vars:
      - name: now
        type: date
        params:
          format: "%d/%m/%Y"
  - trigger: ":id"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: |
            size=20
            chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
            id=""
            for ((i=0; i<size; i++)); do
              rand=$(( RANDOM % ${#chars} ))
              id+="${chars:rand:1}"
            done
            echo "$id"
